const level1 = new Level(
    [
        new NormalChicken(),
        new NormalChicken(),
        new SmallChicken(),
        new SmallChicken(),,
        new NormalChicken(),
        new NormalChicken(),
        new SmallChicken(),
        new SmallChicken(),
    ],
    [
        new Coin(210, 260),
        new Coin(250, 220),
        new Coin(300, 180),
        new Coin(350, 180),
        new Coin(400, 220),
        new Coin(440, 260),
        new Coin(1210, 160),
        new Coin(1250, 120),
        new Coin(1300, 80),
        new Coin(1350, 80),
        new Coin(1400, 120),
        new Coin(1440, 160),
        new Coin(2210, 260),
        new Coin(2250, 220),
        new Coin(2300, 180),
        new Coin(2350, 180),
        new Coin(2400, 220),
        new Coin(2440, 260),
        new Coin(3210, 160),
        new Coin(3250, 120),
        new Coin(3300, 80),
        new Coin(3350, 80),
        new Coin(3400, 120),
        new Coin(3440, 160),
    ],
    [
        new BottleGround('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 1000),
        new BottleGround('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 1500),
        new BottleGround('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 2000),
        new BottleGround('img/6_salsa_bottle/2_salsa_bottle_on_ground.png', 2500),
        new BottleGround('img/6_salsa_bottle/1_salsa_bottle_on_ground.png', 3000),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 719),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObject('img/5_background/layers/air.png', 719 *2),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 *2),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 *2),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 *2),
        new BackgroundObject('img/5_background/layers/air.png', 719 *3),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 *3),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 *3),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 *3),
        new BackgroundObject('img/5_background/layers/air.png', 719 *4),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 *4),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 *4),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 *4),
        new BackgroundObject('img/5_background/layers/air.png', 719 *5),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 *5),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 *5),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 *5),
        new BackgroundObject('img/5_background/layers/air.png', 719 *6),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 *6),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 *6),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 *6),
        new BackgroundObject('img/5_background/layers/air.png', 719 *7),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 *7),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 *7),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 *7),
    ],
    [
        new Cloud('img/5_background/layers/4_clouds/1.png', 0),
        new Cloud('img/5_background/layers/4_clouds/2.png', 500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 1000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 1500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 2000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 2500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 3000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 3500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 4000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 4500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 5000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 5500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 6000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 6500),
        new Cloud('img/5_background/layers/4_clouds/1.png', 7000),
        new Cloud('img/5_background/layers/4_clouds/2.png', 7500),
    ],
    [
        new Endboss(),
    ]
);